version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=db_gerenciamento'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3309:3306'
  app:
    build: .
    container_name: gerenciamento_vendas_docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_gerenciamento
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret

volumes:
  mysql-data: